//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SALESMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public int AUTO_ID { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string CUSTOMER_MOBILE { get; set; }
        public decimal TOTAL_AMOUNT { get; set; }
    }
}
