USE [SALESDB]
GO

/****** Object:  Trigger [dbo].[GENERATE_CHALLAN_ID_NEW]    Script Date: 12/7/2021 1:49:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[GENERATE_INVOICE_NO_NEW]
ON [dbo].[SALES]
INSTEAD OF INSERT
AS
BEGIN
  SET NOCOUNT ON
  INSERT INTO [dbo].[SALES] ([INVOICE_NO]
  , [DATE]
  , [CUSTOMER_MOBILE]
  , [TOTAL_AMOUNT]
 )



    SELECT
      DBO.GET_NEW_INVOICE_NO()
 , [DATE]
  , [CUSTOMER_MOBILE]
  , [TOTAL_AMOUNT]


    FROM INSERTED
    WHERE [INVOICE_NO] IS NULL
END
GO

ALTER TABLE [dbo].[SALES] ENABLE TRIGGER [GENERATE_INVOICE_NO_NEW]
GO


